# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4599d35a2383d1e0da7168e2863213f53f6fb991189d74b2144bf83f9bc387deea1a0a1d74de8faac5ad88d0a3e499b423e83f22c959c10aeafe39a80e6570a1

test:
  secret_key_base: ad71cc8b1c711a2414bb5215cf10a0e55c2c162a0747044c086af9b75d6c9076abf3e9d0ae6bb35760a9b3cc2533f6962288661fae90501606f087c037eb0e3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
